### ISSUE TITLE
Problem when generating styles.css

### ISSUE THREAD

**Issue by localhero44** [angelmtztrc/cra-template-tailwindcss-starter#1]
Hi,
Just trying your nice cra with tailwind starter.
But when I try to generate the styles.css it fails : npm run build-css:develop
> myproject@0.1.0 build-css:develop C:\Users\david\Documents\dev\reacttailwind\myproject
> tailwindcss build tailwind.css -o src/styles.css
   tailwindcss 2.0.1
    Building: tailwind.css
    Error: true is not a PostCSS plugin

I'm lost. Do you understand the problem?

**Comment by angelmtztrc** [comment]
Hi! Mmm... interesting. It's something related to PostCSS, do you modified the `postcss.config.js` file? I already test other time the package and still works.

Does this error occur in all the projects you generate? are you using version *1.2.0* of the package?

```sh
~\Desktop\myproject master
❯ yarn build-css:develop
yarn run v1.22.5
$ tailwindcss build tailwind.css -o src/styles.css

   tailwindcss 2.0.1

   � Building: tailwind.css

   ✅ Finished in 2.39 s
   � Size: 3.97MB
   � Saved to src/styles.css

Done in 3.26s.
~\Desktop\myproject master
❯
``` 

Please, put a screenshot of your `package.json` and you `postcss.config.js`. Or if you have a repo with your project, put the link so I can help you!

**Comment by localhero44** [comment]
Hello,
I haven't modified anything, I just wanted to test your template as I am learning React and TailWind 👍 
So the only commands I have used are : 
- npx create-react-app my-project --template tailwindcss-starter
- cd myproject
- npm install
- npm run build-css:develop

Yes package version 1.2.0.
The Node version I have is 12.19.0
I have tried to create another project, same problem.

**Comment by localhero44** [comment]
There is a discussion with the same errror message here : https://github.com/vercel/next.js/issues/17236
It seems to be related to postcss version.

**Comment by angelmtztrc** [comment]
I see, maybe it's a problem with **autoprefixer**. It is very rare since the problem does not occur to me (and I have already tried on several computers). However, I'm going to update a few things in the template and see if that fixes the problem!

**Comment by localhero44** [comment]
Maybe it is due to the fact that I use npm instead of yarn to generate the styles.css file ?

**Comment by localhero44** [comment]
I'm here because I've seen your post on dev.to yesterday :)

**Comment by angelmtztrc** [comment]
> Maybe it is due to the fact that I use npm instead of yarn to generate the styles.css file ?


I don't think that is the problem, but you can try.

Also, try doing the following:

- Remove your `node_modules` folder
- Install all of the dependencies of the project 
   ```sh
   npm install
   # or
   yarn install
   ``` 
- then run the build CSS script
    ```sh
   npm run build-css:develop
   # or
   yarn build-css:develop
   ``` 


If it doesn't work then wait for me as I try to fix the problem. In the same way, you can try to solve it and send a pull request if you find the source of the error!

**Comment by localhero44** [comment]
I tried removing and reinstall it with npm, same problem.
Then I have installed the modules with yarn, and build the CSS with yarn, it works !

But I don't know what problem it could be by using npm.

**Comment by angelmtztrc** [comment]
Great that it worked with Yarn. I will continue looking for what the problem is. Enjoy your learning!
